// <auto-generated />
using System;
using Aegis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aegis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AegisDbContext))]
    partial class AegisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Aegis.Core.Models.Astronaut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MissionStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NASAId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NASAId")
                        .IsUnique();

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("Aegis.Core.Models.BiometricReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AstronautId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<double>("ZScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("AstronautId", "MetricType");

                    b.ToTable("BiometricReadings");
                });

            modelBuilder.Entity("Aegis.Core.Models.InterventionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AstronautId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EscalateToFlightSurgeon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImmediateActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonitoringFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TriggeredByReadingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AstronautId");

                    b.HasIndex("TriggeredByReadingId")
                        .IsUnique();

                    b.ToTable("InterventionPlans");
                });

            modelBuilder.Entity("Aegis.Core.Models.PersonalBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AstronautId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StdDev")
                        .HasColumnType("REAL");

                    b.Property<double>("SumOfSquaredDeviations")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AstronautId", "MetricType")
                        .IsUnique();

                    b.ToTable("PersonalBaselines");
                });

            modelBuilder.Entity("Aegis.Core.Models.BiometricReading", b =>
                {
                    b.HasOne("Aegis.Core.Models.Astronaut", "Astronaut")
                        .WithMany("BiometricReadings")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");
                });

            modelBuilder.Entity("Aegis.Core.Models.InterventionPlan", b =>
                {
                    b.HasOne("Aegis.Core.Models.Astronaut", "Astronaut")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Core.Models.BiometricReading", "TriggeredByReading")
                        .WithOne()
                        .HasForeignKey("Aegis.Core.Models.InterventionPlan", "TriggeredByReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Astronaut");

                    b.Navigation("TriggeredByReading");
                });

            modelBuilder.Entity("Aegis.Core.Models.PersonalBaseline", b =>
                {
                    b.HasOne("Aegis.Core.Models.Astronaut", "Astronaut")
                        .WithMany("PersonalBaselines")
                        .HasForeignKey("AstronautId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astronaut");
                });

            modelBuilder.Entity("Aegis.Core.Models.Astronaut", b =>
                {
                    b.Navigation("BiometricReadings");

                    b.Navigation("InterventionPlans");

                    b.Navigation("PersonalBaselines");
                });
#pragma warning restore 612, 618
        }
    }
}
